x-airflow-common: &airflow-common-override
  environment:
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
  extra_hosts:
    - "host.docker.internal:host-gateway"
  volumes:
    - ./projects:/opt/airflow/projects # Add this line to the anchor

services:
  airflow-apiserver:
    <<: *airflow-common-override
  airflow-scheduler:
    <<: *airflow-common-override
  airflow-dag-processor:
    <<: *airflow-common-override
  airflow-worker:
    <<: *airflow-common-override
  airflow-triggerer:
    <<: *airflow-common-override
  airflow-init:
    <<: *airflow-common-override