name: Deploy DAGs to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:

      - name: Sync DAGs and Restart
        run: |
          # 1. Go to the folder where your code lives on the server
          cd /opt/airflow-prod
          
          # 1. Fetch and Reset: Discard local changes, match repo exactly
          git fetch origin main
          git reset --hard origin/main
          
          # 2. Rebuild only if necessary: This is fast if no changes occurred
          # If you update requirements.txt or Dockerfile, this ensures changes apply
          # docker compose build
          
          # 3. Restart services: This picks up new DAG files and config changes
          # without wiping your database (volumes).
          # docker compose up -d
          docker compose up -d --build

          # 4. Cleanup: Removes unused images to save disk space
          docker image prune -f